version: "3.9"

services:
  backend:
    build: ./backend
    container_name: url_shortener_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3  # Persist SQLite database
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: url_shortener_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
